services:
  instasaver-bot:
    build: .
    container_name: instasaver-bot
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      # Optional: mount temp directory (with correct user permissions)
      - ./temp:/app/temp

    # Resource limits to prevent container from consuming too much
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 128M
          cpus: '0.25'

    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 60s
      timeout: 10s
      start_period: 30s
      retries: 3

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Security options
    security_opt:
      - no-new-privileges:true

    # Read-only root filesystem (excluding temp directory)
    read_only: true
    tmpfs:
      - /tmp
